### ISSUE TITLE
Release versions?

### ISSUE THREAD

**Issue by zerothi** [HPAC/ReLAPACK#1]
Is ReLAPACK in a usable state?

If so would you mind creating a tag for release?

This makes it obvious to users that a stable version has been attained. :)

**Comment by pauldj** [comment]
Hi, Elmar will reply on Monday. For now, yes, ReLAPACK is in a stable & usable state. I hope it'll help you!

**Comment by elmar-peise** [comment]
Yes, ReLAPACK is stable and useable.  I just created a first release.
We very recently converted all FORTRAN parts of ReLAPACK to C and might still do some refactoring, but I don't expect any changes in its current functionality of interfaces.

**Comment by zerothi** [comment]
Ok, great thanks Paolo and Elmar :)

2016-03-07 16:59 GMT+01:00 Elmar Peise notifications@github.com:

> Yes, ReLAPACK is stable and useable. I just created a first release.
> We very recently converted all FORTRAN parts of ReLAPACK to C and might
> still do some refactoring, but I don't expect any changes in its current
> functionality of interfaces.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HPAC/ReLAPACK/issues/1#issuecomment-193314818.

## 

Kind regards Nick
