### ISSUE TITLE
xGETRF info=4 conditional probably wrong

### ISSUE THREAD

**Issue by martin-frbg** [HPAC/ReLAPACK#4]
While running the lapack testsuite, I noticed that the GETRF functions were getting flagged for 
wrong error exits - in the original LAPACK GETRF, INFO=4 is returned for lda < m while your
code has 
https://github.com/HPAC/ReLAPACK/blob/77dcdeeaa4bbdff8ed93486066277a8f00098f50/src/dgetrf.c#L25

**Comment by elmar-peise** [comment]
Thanks for spotting this!
I updated the condition to check m instead of n.

**Comment by martin-frbg** [comment]
Unfortunately I am seeing several other problems with the LAPACK 3.8.0 testsuite - still trying to determine if these are genuine ReLAPACK bugs or OpenBLAS' fault.
